#!/usr/bin/env bash

export CONTECO_LABEL="package.ingest_journal - ModEco"
export CONTECO_DESCRIPTION="The ModEco ingest module package based on journalbeat.  "

export CONTECO_TYPE="package"
export CONTECO_NAME="ingest_journal"
export CONTECO_TAG="7.9.2"


export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="modeco"
