#!/usr/bin/env bash


prefix="package_$2"

if [[ "package_ingest_journal_journalbeat_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create package_ingest_journal_journalbeat_volume
	fi
	
