#!/usr/bin/env bash


prefix="package_ingest_journal_$2"

if [[ "package_ingest_journal_ingest_journal_journalbeat_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create package_ingest_journal_ingest_journal_journalbeat_volume
	fi
	
